### PR TITLE
Update README.md add install of llvm package

### PR DESCRIPTION
**Pull request by ChakshuGupta**
The build and install steps are missing the installation of "llvm" package which is a pre-requisite for building llvm_mode.

Added the "llvm" package in the installation line.

### CODE REVIEW

**Comment by domenukk** [comment]
Thanks! :)
It's technically not necessary for AFL itself, though, so I'm not sure about listing it here.
I'll wait for the other's optinions.

**Comment by vanhauser-thc** [comment]
for source code as a good part of what makes afl++ amazing is the llvm_mode stuff so it should be added. The issue is however - how? llvm9 is what should be installed however non-current distros (e.g. Ubuntu 16.04, not sure about 18.04) does not have it.

**Comment by ChakshuGupta** [comment]
Okay. noted.

**Comment by vanhauser-thc** [comment]
I will add a text line to the README, not apt install command, I dont see another way.

**Pull request closed without merging**
