### PR TITLE
LLVM 10 build fix proposal

### PR DESCRIPTION
**Pull request by devnexen**
c++14 is the minimum for this version, thus the hardcoded gnu++11
standard flag makes the build fails.
Missing header only for this version seemingly for the option.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
you are saying it needs c++14 to compile but you do not set this in the Makefile ... why?

**Comment by devnexen** [comment]
I allow to override it via LLVM_STDCXX variable in case anyone uses llvm 6 for ex I did not dare to hardcode it.

**Comment by vanhauser-thc** [comment]
yes you allow to override, but if someone does not do it it will still not compile with llvm-10 right? then this is pretty pointless :)
the better move is to detect the llvm version and set the c++14 version flag if its 10 or higher

**Comment by vanhauser-thc** [comment]
thanks!

**Pull request merged**
