### PR TITLE
Add LTO collision free llvm_mode

### PR DESCRIPTION
**Pull request by vanhauser-thc**
This PR adds a collision free coverage of the target in llvm_mode

It adds the following new executables:
 - afl-ld

It adds the following new passes:
 - afl-llvm-lto-instrumentation.so.cc 
 - afl-llvm-lto-whitelist.so.cc

It modifies afl-clang-fast.c and the Makefile to also create a new linked version: afl-clang-lto/afl-clang-lto++

The README.lto.md explains the new compile mode

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
it is done now. all issues resolved and it works great! 10-15% more speed and no collisions!

**Comment by andreafioraldi** [comment]
```/usr/lib/llvm-8/bin/clang -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/lib/llvm-8/bin\" -DVERSION=\"++2.62d\" -DLLVM_VERSION=\"8.0.0\"  -DAFL_CLANG_FLTO=\"-flto=full\" afl-ld.c -o ../afl-ld  -DAFL_REAL_LD=\"\"
ln -sf afl-ld ../ld

[-] PROGRAM ABORT : Unable to find 'afl-llvm-rt.o' or 'afl-llvm-pass.so'. Please set AFL_PATH
         Location : find_obj(), afl-clang-fast.c:132

```

Is this error normal during compilation of llvm mode?

**Comment by andreafioraldi** [comment]
@vanhauser-thc you should add the compilation time of the tested libs in the readme so that the users can have an idea about the overhead. I'll give you also the FFmpeg compilation time on my laptop when it'll finish.

**Comment by andreafioraldi** [comment]
Sad story, on Ubuntu the dault path of ld is not /bin/ld, but /usr/bin/ld.

```
LD	ffmpeg_g
LD	ffprobe_g
fftools/ffmpeg_opt.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
fftools/cmdutils.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:114: recipe for target 'ffmpeg_g' failed
make: *** [ffmpeg_g] Error 1
make: *** Waiting for unfinished jobs....
Makefile:114: recipe for target 'ffprobe_g' failed
make: *** [ffprobe_g] Error 1
```

**Comment by andreafioraldi** [comment]
Same issue after moving afl-ld to /usr/bin/ld

```
andrea@malweisse:~/FFmpeg$ export AFL_REAL_LD=/usr/bin/ld.orig
andrea@malweisse:~/FFmpeg$ time make CC=~/Videos/AFLplusplus/afl-clang-lto CXX=~/Videos/AFLplusplus/afl-clang-lto++ -j8
LD	ffmpeg_g
LD	ffprobe_g
fftools/ffmpeg_opt.o: file not recognized: File format not recognized
fftools/cmdutils.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
Makefile:114: recipe for target 'ffmpeg_g' failed
make: *** [ffmpeg_g] Error 1
make: *** Waiting for unfinished jobs....
Makefile:114: recipe for target 'ffprobe_g' failed
make: *** [ffprobe_g] Error 1
```

**Comment by vanhauser-thc** [comment]
@andreafioraldi 

I have never seen that error. Not happening for me when I do "make clean ; make ; cd llvm_mode ; make"

For the compilation time: it is small to big, depending on what it is. if it is a big library that has 100+ example tool it will take long because 100+ the big library is basically recompiled every time. In non-library compilations or libraries with few examples or just one binary the overhead is neglectable... what do you propose to write in the README.lto?

**Comment by andreafioraldi** [comment]
If the overhead is neglectable, the readme is fine as it is

**Comment by andreafioraldi** [comment]
Ubuntu 18.04

**Comment by domenukk** [comment]
One thing I wonder, why keep the older instrumentations around at all?

**Comment by vanhauser-thc** [comment]
There are targets that don’t compile with clang so we need afl-gcc. 
LTO will have more targets that will not work (a guess).

For the type of instrumentation - edge insertion - this needs a special functionality that we only have in llvm. And it is frickle. O3 destroys the CFG with llvmgold so I need to downgrade to O2 by intercepting the command option. Also how you perform the inserting can fuck things up. I managed to solve this here but a future llvm might fuck things up again and then it is important to have an alternative.

**Comment by domenukk** [comment]
One alternative, yes. But I currently have afl-clang, afl-clang-fast and afl-clang-lto compiled in my afl folder, I suggest at least making the old ones optional.

**Comment by vanhauser-thc** [comment]
2/3 of my tested targets work fine - even libxml and exiv, 1/3 fail - with two types of errors why.

I am on vacation without a laptop until Sunday.

I will merge now, and then work through the bug reports starting Sunday.
Maybe someone even will send a PR :)

I created a special issue for collecting problems: https://github.com/vanhauser-thc/AFLplusplus/issues/226

**Comment by vanhauser-thc** [comment]
@domenukk if you execute afl-clang it will tell you it is deprecated. (and its a symlink to afl-gcc)

**Pull request merged**
