### PR TITLE
Add last path, crash, hangs for `afl-whatsup`

### PR DESCRIPTION
**Pull request by chibinz**
Add path, crash, hangs, more to come.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
I agree to fuzzah comments:
https://github.com/vanhauser-thc/AFLplusplus/issues/256#issuecomment-599042845_

I also like his other ideas in a previous comment however that is nothing you have to implement.
getting what is already in this PR right is fine with me.

**Comment by chibinz** [comment]
OK, I will improve on it.

**Comment by domenukk** [comment]
Thanks for the PR. I definitely like the extended summary! 
However I have some issues:
 
When I try to run `afl-whatsup` in _zsh_, I get:
```bash
Individual fuzzers
==================

/home/users/dmaier/baseband/AFLplusplus/afl-whatsup: 95: /home/users/dmaier/baseband/AFLplusplus/afl-whatsup: function: not found
/home/users/dmaier/baseband/AFLplusplus/afl-whatsup: 97: [: -eq: unexpected operator
/home/users/dmaier/baseband/AFLplusplus/afl-whatsup: 101: local: not in a function
``` 
I can fix this by replacing `/bin/sh` with `/bin/bash` (not sure if we want bash as dependency, though?).

Apart from that, listing all fuzzers takes rather long, plus I have some rendering issues for some of the fuzzers, for example:
```bash
>>> 56 (4 days, 13 hrs) fuzzer PID: 941 <<<                                       
                                                            
  last_path  : 5 hours, 53 minutes                     
  last_crash : none seen yet                                  
  last_hang  : none seen yet                                   
  cpu usage 5.5                                               
0.0                                                                                                              
0.0                                                                                                  
10.2%, memory usage 0.0                                       
0.0                                                                                                                              
0.0                                                                            
0.0%                                                                              
  cycle 79, lifetime speed 133 execs/sec, path 532/1709 (31%) 
  pending 460/1709, coverage 9.46%, no crashes yet  
```

**Comment by hexcoder-** [comment]
*BSD do not have bash as the default. I already put portability work into afl++ to avoid bash dependencies...

**Pull request closed without merging**
