### PR TITLE
Basic docker build proposal.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Seems fine, great, thank you!

**Comment by vanhauser-thc** [comment]
I disagree, sorry.
For docker we want llvm 9 and gcc 9. anything older is bad as the performance improvement is quite noticable.

**Comment by devnexen** [comment]
> I disagree, sorry.
> For docker we want llvm 9 and gcc 9. anything older is bad as the performance improvement is quite noticable.

Ah yes the never zero part ... forgot.

**Comment by vanhauser-thc** [comment]
its not only the notzero for llvm, for radamsa (upcoming in a few days I hope) gcc9 is required as it is faster with it. and faster is ... still very slow ;)

Thanks!

**Pull request merged**
