### PR TITLE
packages at readme

### PR DESCRIPTION
**Pull request by ankit2001**
while doing make distrib , i need some packages preinstalled in ubuntu to run afl++, i have added them

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
the .8 files are in there by error in your PR.

other packages that should be there are:
build-essential libtool-bin python pixman clang

**Comment by ankit2001** [comment]
I think .8 files came automatically after building with make, let me fix

**Comment by domenukk** [comment]
Thanks :)

**Comment by ankit2001** [comment]
@domenukk I am interested in making ml project for aflplusplus for gsoc, I want you to be as mentor

**Pull request merged**
