### PR TITLE
Little compiler plugins rework regarding block location picked up.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by hexcoder-** [comment]
Thanks, what is the motivation/gain for making the compile time random values seeded with time?
Are there collisions?

**Comment by devnexen** [comment]
To make it consistent with the gcc plugin above all

**Comment by hexcoder-** [comment]
I see. @vanhauser-thc: should we sync llvm_mode to gcc_plugin or vice versa?

**Comment by vanhauser-thc** [comment]
it just improves the random number generation a bit, nothing wrong with that, so its nice to have

**Pull request merged**
