### PR TITLE
Port for Android

### PR DESCRIPTION
**Pull request by JoeyJiao**
Orig from android-afl,
Example to build this for android using llvm:
export AFL_TRACE_PC=true
mm

Example to enable android-test with afl:
cd android-test
TEST_CLANG_FAST_AARCH64=true mm

### CODE REVIEW

**Comment by hexcoder-** [comment]
Thanks for your contribution!

There seem to be some changes that are not strictly related to Android (like [llvm7 and AFLTRACE_PC=1](https://github.com/vanhauser-thc/AFLplusplus/pull/28/commits/dbf59fdccc3f670edd8bb9b9b45f2d8fbf41122e) or the test file crash.c).
I would like to add some tests, but once for all supported platforms.

The integration of ashmem is very clean (and does only minimally touch the afl++-sources) ++.
Is it correct, that only llvm_mode (aka afl-clang-fast) is currently supported , but not afl-clang or afl-gcc?

I am not so happy with a separate Makefile for android, because it raises the maintenance costs for all future changes. 
Could it be possibly integrated with our main Makefile?

Thank again!

**Comment by vanhauser-thc** [comment]
Hey some feedback from me:

I agree that there should only be one Makefile. @JoeyJiao if you have difficulties to combine them I can help you (although I dont know what would work on Android)

also - why did you rename llvm_mode/afl-llvm-pass.cc  to llvm_mode/afl-llvm-pass.cpp? 
Dont. really dont. all c++ files in the project have a .cc extensions. and original afl introduced that, and thats why its not changed (although I dont like .cc either)

**Comment by JoeyJiao** [comment]
llvm_mode/afl-llvm-pass.cc to llvm_mode/afl-llvm-pass.cpp? => if using cc, Android complains that the alf-llvm-pass.o.cc not used.
And android-test is put there to verify if the built afl-clang-fast works, but it can be removed if having other test cases.

**Comment by JoeyJiao** [comment]
For the Makefile, I don't know there is way Android accepts. As far as I know, Android only accepts Android.mk and Android.bp to build.

**Comment by vanhauser-thc** [comment]
@JoeyJiao ah ok, so seems there really is not much you could change/fix.

for the .cc -> .cpp - how about if the llvm_mode Makefile creates a symlink from .cc -> .cpp if Android is detected? that would be better IMHO

**Comment by hexcoder-** [comment]
For the Makefile we could also try with a symlink.

**Comment by vanhauser-thc** [comment]
Hey, what is happening with the PR @JoeyJiao ?

I am more than happy to support Android here, but it must be in a way that is compatible as otherwise the Android port part will become outdated and not compile etc. and that is not a good thing for afl++ or for people who want to use it on Android.

So ... using symlinks would be the best way if thats possible. have you tested it?

**Comment by JoeyJiao** [comment]
> Hey, what is happening with the PR @JoeyJiao ?
> 
> I am more than happy to support Android here, but it must be in a way that is compatible as otherwise the Android port part will become outdated and not compile etc. and that is not a good thing for afl++ or for people who want to use it on Android.
> 
> So ... using symlinks would be the best way if thats possible. have you tested it?

I tried to delete the Android.mk and ln -s Makefile Android.mk, but the build failed: ninja: error: unknown target 'MODULES-IN-AFLplusplus'.
Per my understanding to Android, it's another build system other than make, so I don't think the symbol link way will work.

**Comment by vanhauser-thc** [comment]
of course just symlinking will not work as some variables are not set.

can you please try the following:

mv Android.mk Makefile.test
ln -s Makefile.test Android.mk

and then try to build ... does that work?
If so the symlink solution works and we would "just" need to modify our Makefile

**Comment by JoeyJiao** [comment]
> of course just symlinking will not work as some variables are not set.
> 
> can you please try the following:
> 
> mv Android.mk Makefile.test
> ln -s Makefile.test Android.mk
> 
> and then try to build ... does that work?
> If so the symlink solution works and we would "just" need to modify our Makefile

I tried to mv Andorid.mk Makefile.test && ln -s Makefile.test Android.mk, build succeed.

so I just upload the changes excluding the Android.mk at the moment.

**Comment by vanhauser-thc** [comment]
please also change back the .cpp to .so.cc - then I can accept the PR.
I will see how to get the Android.mk file + llvm_mode stuff to work. but as I dont have Android you will need to test that :)

**Comment by JoeyJiao** [comment]
> please also change back the .cpp to .so.cc - then I can accept the PR.
> I will see how to get the Android.mk file + llvm_mode stuff to work. but as I dont have Android you will need to test that :)

Updated, pls check again.
And for sure, will test once new Makefile ready

**Comment by vanhauser-thc** [comment]
I am currently in on a time extensive customer project, I will check it out on Friday+ or so

**Comment by vanhauser-thc** [comment]
can you please attack your original Android.mk file here?

**Comment by vanhauser-thc** [comment]
@JoeyJiao can you please attach here your original Android.mk to a comment ?

**Comment by hexcoder-** [comment]
[Google developer guide for Android.mk](https://developer.android.com/ndk/guides/android_mk)

(serves as a bookmark for me)

**Pull request merged**
