### PR TITLE
qemu mode: enabling other platforms if possible.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@andreafioraldi ?

**Comment by andreafioraldi** [comment]
I'm 100% sure that this will not work for macOS. QEMU user is supported for BSD but I never used it and I don't know the state and the percentage of compatibility. Remove the references to Darwin and test it on *BSD please.

**Comment by andreafioraldi** [comment]
@devnexen why `--no-check-certificate`? We download QEMU directly from the official website and if the certificate of qemu.org expires is better to not download at all.

**Comment by andreafioraldi** [comment]
also, libcompcov is a linux-only library, insert an if statement before calling make -C libcompcov

**Comment by devnexen** [comment]
Because of NetBSD ... does not handle SSL in their packages (as git and so on)

**Comment by krytarowski** [comment]
NetBSD does handle SSL, there is need to install mozilla-rootcerts.

**Comment by krytarowski** [comment]
On the other hand... qemu bsd-user is broken since ever. There are downstream FreeBSD patches for it but they never hit the upstream tree.

**Comment by andreafioraldi** [comment]
I think that, in addition, the patches to the files into linux-user/ should be ported to bsd-user in order to make it work.

**Comment by devnexen** [comment]
regardin

**Pull request closed without merging**
