### PR TITLE
test, /sbin not necessarily in the path os casual users.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by hexcoder-** [comment]
Thanks, this is probably always valid on Linux...

**Comment by vanhauser-thc** [comment]
I had to fix this. not all sysctl are in /sbin. e.g. on systems with busybox ...

**Comment by devnexen** [comment]
The second call passes ?

**Comment by vanhauser-thc** [comment]
ah overlooked the second one, thanks

**Pull request merged**
