### PR TITLE
Moved unicorn_mode to unicornafl

### PR DESCRIPTION
**Pull request by domenukk**
This pull request uses the newly patched version of unicorn instead of the original unicorn-afl.
One potential regression, this has _not_ been tested on any non-linux system.
Specifically, I heard mmaping files into the address space might break on some BSDs(?)
https://github.com/vanhauser-thc/unicorn/blob/c15508a3731d42fdd3b1a98d72ff80e2597def6b/afl.c#L59

Also, to be discussed: 
I have now actually added unicorn as git submodule. This makes it really easy to navigate the sources on github and keep track of changes. In my personal opinion this is the right way as it is what everybody else uses.
Another option (maybe for the future) could be to install unicornafl from PyPI directly.

With the move to unicornafl, the api changed slightly:
The forkserver no longer starts on the very first instruction, but whenever `uc.afl_start_forkserver` or imply `uc.afl_fuzz` gets called.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
looks like great work however I have little clue there :)

@andreafioraldi ?

**Comment by andreafioraldi** [comment]
I already talked with Dominik about the api change. I support it, the previous design with the hook on the first instruction is crappy.
btw why Travis fails?

**Comment by andreafioraldi** [comment]
Travis fails with -lunicorn not found. Full build log [here](https://pastebin.com/tfv8kxii).

**Comment by andreafioraldi** [comment]
```
  LINK    sample_arm
 
  LINK    sample_armeb
 
/usr/bin/ld: cannot find -lunicorn
 
/usr/bin/ld: cannot find -lunicorn
 
collect2: error: ld returned 1 exit status
 
collect2: error: ld returned 1 exit status
 
Makefile:104: recipe for target 'sample_armeb' failed
 
make[2]: *** [sample_armeb] Error 1
 
make[2]: *** Waiting for unfinished jobs....
 
Makefile:104: recipe for target 'sample_arm' failed
 
make[2]: *** [sample_arm] Error 1
 
make[2]: Leaving directory '/home/travis/build/vanhauser-thc/AFLplusplus/unicorn_mode/unicorn/samples'
 
Makefile:229: recipe for target 'all' failed
 
make[1]: *** [all] Error 2
 
make[1]: Leaving directory '/home/travis/build/vanhauser-thc/AFLplusplus/unicorn_mode/unicorn'
 
Makefile:325: recipe for target 'distrib' failed
 
make: *** [distrib] Error 1
 
The command "if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_CPU_ARCH" = "amd64" ]; then make distrib ; fi" exited with 2.
 
0.00s$ if [ "$TRAVIS_CPU_ARCH" = "arm64" ] ; then make ; cd qemu_mode && sh ./build_qemu_support.sh ; cd .. ; fi
 
The command "if [ "$TRAVIS_CPU_ARCH" = "arm64" ] ; then make ; cd qemu_mode && sh ./build_qemu_support.sh ; cd .. ; fi" exited with 0.```

**Comment by domenukk** [comment]
I seem to struggle to get the environment of the Travis build right. Locally it works (works for me...) What's an easy way to debug this? More prints?

**Comment by domenukk** [comment]
> lunicorn

Ah I guess this should now be lunicornafl...

**Comment by vanhauser-thc** [comment]
@domenukk yes - more prints is how. at least I found no other way :)

if it works for you but fails on travis its likely that packages are installed or custom libraries that are not in the travis build.

**Comment by andreafioraldi** [comment]
Wait @vanhauser-thc why libcompcov fails to build? There are weird errors
```[*] Testing the build...

make[1]: python3.7m-config: Command not found

make[1]: Entering directory `/home/travis/build/vanhauser-thc/AFLplusplus'

make[1]: python3.7m-config: Command not found

make[1]: python3.7m-config: Command not found

[+] Instrumentation tests passed. 

[+] All set, you can now use the -Q mode in afl-fuzz!

[+] Building libcompcov ...

make[1]: Entering directory `/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/libcompcov'

gcc -O3 -funroll-loops -I ../../include/ -Wall -Wno-unused-result -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -shared -fPIC libcompcov.so.c -o ../../libcompcov.so -ldl

g++ compcovtest.cc -o compcovtest 

In file included from /usr/include/c++/4.8/cstdint:35:0,

                 from compcovtest.cc:23:

/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

 #error This file requires compiler and library support for the \

  ^

compcovtest.cc: In function ‘int main()’:

compcovtest.cc:41:3: error: ‘uint64_t’ was not declared in this scope

   uint64_t x = 0;

   ^

compcovtest.cc:41:12: error: expected ‘;’ before ‘x’

   uint64_t x = 0;

            ^

compcovtest.cc:42:10: error: ‘x’ was not declared in this scope

   fread(&x, sizeof(x), 1, stdin);

          ^

compcovtest.cc:45:3: error: ‘uint32_t’ was not declared in this scope

   uint32_t y = 0;

   ^

compcovtest.cc:45:12: error: expected ‘;’ before ‘y’

   uint32_t y = 0;

            ^

compcovtest.cc:46:10: error: ‘y’ was not declared in this scope

   fread(&y, sizeof(y), 1, stdin);

          ^

compcovtest.cc:49:3: error: ‘uint16_t’ was not declared in this scope

   uint16_t z = 0;

   ^

compcovtest.cc:49:12: error: expected ‘;’ before ‘z’

   uint16_t z = 0;

            ^

compcovtest.cc:50:10: error: ‘z’ was not declared in this scope

   fread(&z, sizeof(z), 1, stdin);

          ^

make[1]: *** [compcovtest] Error 1

make[1]: Leaving directory `/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/libcompcov'

[+] Building unsigaction ...

make[1]: Entering directory `/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/unsigaction'

gcc -m32 -fPIC -shared unsigaction.c -o unsigaction32.so

/usr/bin/ld: cannot find crti.o: No such file or directory

/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc.a when searching for -lgcc

/usr/bin/ld: cannot find -lgcc

/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc_s.so when searching for -lgcc_s

/usr/bin/ld: cannot find -lgcc_s

/usr/bin/ld: cannot find -lc

/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc.a when searching for -lgcc

/usr/bin/ld: cannot find -lgcc

/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc_s.so when searching for -lgcc_s

/usr/bin/ld: cannot find -lgcc_s

/usr/bin/ld: cannot find crtn.o: No such file or directory

collect2: error: ld returned 1 exit status

make[1]: *** [lib_i386] Error 1

make[1]: Leaving directory `/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/unsigaction'

[+] libcompcov ready```

**Comment by andreafioraldi** [comment]
```c
../afl.c: In function ‘uc_afl_fuzz’:

../afl.c:191:5: error: ‘for’ loop initial declarations are only allowed in C99 mode

     for (uint32_t i = 0; persistent_iters == 0 || i < persistent_iters; i++) {

     ^

../afl.c:191:5: note: use option -std=c99 or -std=gnu99 to compile your code
```
@domenukk don't use c99

**Comment by andreafioraldi** [comment]
In test.sh PY is /opt/pyenv/shims/python that is a shell script and so afl-fuzz fails to execute in test.sh. All the other stuffs are now solved.

**Comment by domenukk** [comment]
Ok I'll push some builds with more prints...
BTW @vanhauser-thc for public repos you can ask to enable debug mode at support@travis-ci.com then sshing into the container is possible https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode

**Comment by andreafioraldi** [comment]
`Traceback (most recent call last):

  File "../unicorn_mode/samples/simple/simple_test_harness.py", line 21, in <module>

    from unicornafl import *

ImportError: No module named unicornafl`

**Comment by domenukk** [comment]
My guess is it's installed to a different python location/virtalenv, by grabbing the binary directly we might "break out" of it

**Comment by vanhauser-thc** [comment]
> Ok I'll push some builds with more prints...
> BTW @vanhauser-thc for public repos you can ask to enable debug mode when mailing [support@travis-ci.com](mailto:support@travis-ci.com) then sshing into the container is possible https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode

sent an email to request this

**Comment by vanhauser-thc** [comment]
> My guess is it's installed to a different python location/virtalenv, by grabbing the binary directly we might "break out" of it

you can do some "find" command in the travis script

**Comment by domenukk** [comment]
Unicorn is fixed.
This (unrelated) error remains:
```bash
[+] Building unsigaction ...

make[1]: Entering directory '/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/unsigaction'

gcc -m32 -fPIC -shared unsigaction.c -o unsigaction32.so || echo "Cannot build unsigation32"

/usr/bin/ld: cannot find crti.o: No such file or directory

/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc

/usr/bin/ld: cannot find -lgcc

/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc

/usr/bin/ld: cannot find -lgcc

collect2: error: ld returned 1 exit status

Cannot build unsigation32

gcc -fPIC -shared unsigaction.c -o unsigaction64.so

make[1]: Leaving directory '/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/unsigaction'
```

**Comment by andreafioraldi** [comment]
> Unicorn is fixed. (the `typing` packages isn't preinstalled on python2...)
> This (unrelated) error remains:
> 
> ```shell
> [+] Building unsigaction ...
> 
> make[1]: Entering directory '/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/unsigaction'
> 
> gcc -m32 -fPIC -shared unsigaction.c -o unsigaction32.so || echo "Cannot build unsigation32"
> 
> /usr/bin/ld: cannot find crti.o: No such file or directory
> 
> /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
> 
> /usr/bin/ld: cannot find -lgcc
> 
> /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
> 
> /usr/bin/ld: cannot find -lgcc
> 
> collect2: error: ld returned 1 exit status
> 
> Cannot build unsigation32
> 
> gcc -fPIC -shared unsigaction.c -o unsigaction64.so
> 
> make[1]: Leaving directory '/home/travis/build/vanhauser-thc/AFLplusplus/qemu_mode/unsigaction'
> ```

This is not an error, the script doesn't fail. It tries to build unsigaction32 with -m32 and fails due to the lack of 32 bit libs but as you can see this does not make the script fail (there is an OR with `echo "Cannot build unsigation32"`)

The error is this: ```Installed /home/travis/.local/lib/python2.7/site-packages/typing-3.7.4.1-py2.7.egg

Searching for ctypes

Reading https://pypi.org/simple/ctypes/

No local packages or working download links found for ctypes

error: Could not find suitable distribution for Requirement.parse('ctypes')

Makefile:325: recipe for target 'distrib' failed

make: *** [distrib] Error 1
```
ctypes is not found (??? it should be in the py2 stdlib)

**Comment by andreafioraldi** [comment]
At least now 2/4 of builds succedded. The other 2 (`NAME="trusty-amd64" MODERN="no" GCC="4.8"` and ` NAME="xenial-arm64" MODERN="no" GCC="5" EXTRA="libtool-bin clang-6.0" AFL_NO_X86="1" CPU_TARGET="aarch64" `) fails always with `ImportError: No module named unicornafl`

**Comment by andreafioraldi** [comment]
Ok for ARM64 we should add a check to test.sh to not run unicorn cose it is not built. For the other IDK, it doesn't build unicorn and for a strange reason `if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_CPU_ARCH" = "amd64" ]; then make distrib ; fi` is not called.

**Comment by andreafioraldi** [comment]
Yeah but now we inserted the right dependecies, it's unlikely that setup.py will be touched.
Andrea 1 Travis 0
I'll merge the PR

**Pull request merged**
