### PR TITLE
Add AFL Unicorn

### PR DESCRIPTION
**Pull request by domenukk**
Starting this PR now to start a discussion and get this merged at some point.
Some things:

1. I based this off the original AFL-Unicorn which—in turn—was based on a AFL github mirror. This leads to a massive amount of commits in this PR. Looking for a good way to get rid of them without losing the original blame (git ninjas?)
2. The original AFL-Unicorn is based on the latest official release of Unicorn which is ancient. Instead, I forked the unicorn master and added the patches directly into the repo for now. This feels wrong still. The forked repo now lives on my github, makes no sense to depend on it for alfpp. Looking for a better way. As a point of reference: Unicorn and the included patches are roughly similar to QEMU and the QEMU-AFL patches.

Open for any ideas regarding theses points.
Apart from that, it seems to work. :)

### CODE REVIEW

**Comment by hexcoder-** [comment]
Thanks, being a QEMU cousin I suggest @andreafioraldi have a look.

**Comment by vanhauser-thc** [comment]
@hexcoder- @andreafioraldi - I emailed with dominik about this.

the changes in afl-fuzz and the other tools are small and have no impact on other mode and functionality so this is good (and stable, there should not be changes in the future)

I have a bad feeling with these many commits fucking this repository up though. I dont mind the unicorn stuff, but the mcarpenter ones look horrific IMHO in the fork overview.

Everyone who did something for afl is documented in the docs/ directory as contributors, and the originals contributors are not in the commits anyway.

for unicorn ... I am fine if they are in, although extracting them and adding a CONTRIBUTORS file would also be an option 

so for me - please get rid of the afl commits somehow

**Comment by domenukk** [comment]
Couldn't agree more. I'll sqash them to a single commit then.

**Comment by domenukk** [comment]
@vanhauser-thc as promised, here as a single commit.

**Comment by vanhauser-thc** [comment]
thanks!

**Comment by vanhauser-thc** [comment]
had to put a workaround in the build script but then everything worked :)
and updated readme, changelog and patches to give credit

**Comment by domenukk** [comment]
@vanhauser-thc can you add `Nathan Voss` to the special thanks list (if that's what it's for)? He's the original author of Unicorn-AFL

**Pull request merged**
