### PR TITLE
Concealing the no build test to apple devices.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
to fix [139](https://github.com/vanhauser-thc/AFLplusplus/issues/139)

**Comment by vanhauser-thc** [comment]
so when compiling for iOS then it would try to build? because iOS != Darwin?

the correct fix is to not set LLVM_UNSUPPORTED if its LLVM10.
and LLVM_UNSUPPORTED should not disable the build, just warn and still try - unless we know it wont build (like with apple's Xcode)

**Comment by devnexen** [comment]
Ok tested with Ubuntu with the LLVM PPA repo and Mac when it fails as expected.

**Comment by vanhauser-thc** [comment]
thanks!. that UNSUPPORTED thing was a bug I introduced.

**Pull request merged**
