### PR TITLE
Unicorn mode for BSD proposal.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@hexcoder- @andreafioraldi  - please have a look :)

**Comment by andreafioraldi** [comment]
I don't like to have many build scripts. @devnexen can you integrate this into the old build script?

**Comment by devnexen** [comment]
I could but I fear it would get dirtier and dirtier by adding more platforms.

**Comment by devnexen** [comment]
What os is this ? Normally you should not need -isysroot flag though.

**Comment by hexcoder-** [comment]
Thats Ubuntu bionic 18.04.3 LTS linux.

**Comment by vanhauser-thc** [comment]
> Thanks! @vanhauser-thc: Any idea what is causing this weird travis build fail?
> name collision?
> 
> ```
> /usr/local/clang-7.0.0/bin/clang++ `llvm-config --cxxflags` -Wl,-znodelete -fno-rtti -fpic -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -I ../include/ -DVERSION=\"++2.58d\" -Wno-variadic-macros -DLLVMInsTrim_EXPORTS -fno-rtti -fPIC -std=gnu++11 -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config --ldflags` 
> afl-llvm-pass.so.cc:34:10: fatal error: 'list' file not found
> #include <list>
>          ^~~~~~
> 1 error generated.
> Makefile:173: recipe for target '../afl-llvm-pass.so' failed
> ```

fixed, your comment on the commit was correct.

**Comment by vanhauser-thc** [comment]
ignore the build failure for now, there is one more issue in our testing script that we need to fix, has nothing to do with your PR (yet)

**Comment by hexcoder-** [comment]
I had a second look. Is there a tool for reporting the number of cores available in *BSD and Darwin?
Then we could avoid hardcoding -j4 in make. Other than that, I am fine with it.

**Comment by devnexen** [comment]
There is but it is a bit verbose we might need to trim words
`hw.ncpu: 8`

**Comment by vanhauser-thc** [comment]
please note that I made a change to the unicorn build script

**Comment by vanhauser-thc** [comment]
the build check fails because of:

```
aving to: ‘24f55a7973278f20f0de21b904851d99d4716263.tar.gz’

24f55a7973278f20f0d     [   <=>              ]   3.18M  7.28MB/s    in 0.4s    

2019-11-07 13:45:38 (7.28 MB/s) - ‘24f55a7973278f20f0de21b904851d99d4716263.tar.gz’ saved [3337409]

[-] Error: signature mismatch on 24f55a7973278f20f0de21b904851d99d4716263.tar.gz (perhaps download error?).

Makefile:273: recipe for target 'distrib' failed

make: *** [distrib] Error 1
```

and that is only in your PR, doesnt matter how often I restart the build test.

**Comment by devnexen** [comment]
Yes I did a typo during one commit ...

**Comment by vanhauser-thc** [comment]
so this time it was not ***** travis but it actually caught a bug. that a first! :)

**Pull request merged**
