### PR TITLE
Add tutorial for fuzzing LAVA-M

### PR DESCRIPTION
**Pull request by chibinz**
A beginner's guide for using AFL++

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Hi @chibinz , thank you for the effort.
Sorry but we don't accept tutorials in the main repo, we publish them on the website not here.
In addition, I don't feel that we need a LAVA-M tutorial.
I'm against this type of benchmarking and I don't want that AFL++ encourages users to use LAVA-M and similar datasets that represent nothing.
I you want to contribute with a tutorial, submit a PR that adds a file [here](https://github.com/andreafioraldi/AFLplusplus-website/tree/master/content/docs/tutorials) targetting a real application.

**Comment by andreafioraldi** [comment]
You can however put it on your personal blog maybe or something similar. Using CmpLog, you can almost fully solve all the injected bugs in LAVA-M, but you can do it also building a dictionary using cmp tokens extracted with objdump. If you do that, I can link your blogpost in the AFL++ website, but I'll not include a tutorial using LAVA-M directly for the reasons explained above.

**Comment by chibinz** [comment]
OK, I see your points.

**Comment by vanhauser-thc** [comment]
I would add that is is very short for a tutorial and not really explaining a lot - so little what someone is learning beside copy-paste.

Make a more comprehensive tutorial, put in a blog or github repo, and we we link to it from the readme. this also gives more visibility to your work.

**Pull request closed without merging**
